name: Update Fork and Create Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update fork
        run: |
          git remote add upstream https://github.com/gnat/surreal.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main

      - name: Get package version
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Check if release exists
        id: check_release
        run: |
          release_exists=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/AnswerDotAI/surreal/releases/tags/v${{ steps.package-version.outputs.version }})
          if [ $release_exists -eq 200 ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          release_name: Release v${{ steps.package-version.outputs.version }}
          body: |
            Release of version ${{ steps.package-version.outputs.version }}
            
            Please refer to the [changelog](https://github.com/gnat/surreal/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
